### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by karianna** [joular/joularjx#14]
Hi there,

Are there plans to support the Aarch64 (Arm) platform?

**Comment by adelnoureddine** [comment]
Currently, we support various Raspberry Pi devices and soon Asus Tinker Board (#11), both under Linux on an ARM distribution.
For aarch64, we support Raspberry Pi 4 and Raspberry Pi 400.

JoularJX itself can run fine on aarch64 with the appropriate Java version, and we use our own regression power model ([from our research paper](https://hal.science/hal-03912723v1), and published [in this repo](https://github.com/joular/powermodels)).
So when we build new models, or other models are available, I'll be glad to integrate them to JoularJX.

**Comment by karianna** [comment]
OK, I'll close this and raise specific platforms as needed, thank you!
