### ISSUE TITLE
Better organize generated power files

### ISSUE THREAD

**Issue by adelnoureddine** [joular/joularjx#18]
With the upcoming version 2.0, we will have many files generated (if the user activates all features). JoularJX should organize these files in a better way.

For instance, in a tree hierarchy: results/{app,all}/{runtime,total}/{calltree,methods}

**Comment by JeremyNison** [comment]
After some discussions with @adelnoureddine , we agreed on the following file hierarchy : 
<img width="275" alt="joularjx-rfs" src="https://user-images.githubusercontent.com/77154585/216357607-bb2c08d5-c8a0-4b8b-a6fe-d28e80b8f894.png">
The folders will be created depanding on the selected configurations options.
