### ISSUE TITLE
Small typo in build instruction of the GUI

### ISSUE THREAD

**Issue by MagielBruntink** [joular/joularjx#31]
https://github.com/joular/joularjx/blob/180eb107a5f252de31e71a818425e03e42a0f468/README.md?plain=1#L140

Should be:
```
msbuild.exe joularjx-gui.sln /property:Configuration=Release
```

**Comment by dcompanykrish** [comment]
Can I work on the issue? I am new to open source 😄 , I'm available to work on it. Can I help?
I’m ready to contribute
