### ISSUE TITLE
Monitoring loop exits prematurely

### ISSUE THREAD

**Issue by metacosm** [joular/joularjx#42]
The issue comes from the fact that the `DestroyJavaVM` Thread is actually present before the VM is scheduled to be destroyed in a lot of contexts (in particular, for daemon-like processes) where the VM isn't actually shutting down.

**Comment by adelnoureddine** [comment]
I'll reopen this issue and revert the changes, because JoularJX agent is running continuously even after the program ends.
I'll keep it open until a better solution is found.

**Comment by metacosm** [comment]
Makes sense. Sorry for the issue.

**Comment by adelnoureddine** [comment]
@metacosm, do you have any additional insights about this issue?
Because otherwise, I'm looking to close it.

**Comment by metacosm** [comment]
I haven't looked into it, to be honest. I don't have any idea off the top of my head to address the issue in both cases.

**Comment by adelnoureddine** [comment]
Thanks, I'll close the issue for now, and if anything new comes by, I'll reopen it.
