### ISSUE TITLE
JoularJX doesn't monitor the program consumption, displays 0 Joules (AMD Processor)

### ISSUE THREAD

**Issue by AleMaffe** [joular/joularjx#63]
I would like to report a problem related to the fact that JoularJX does not monitor the correct value of the consumption of my Java program.

I installed the newest version of the program in repo. JoularJX starts at the same time as the program as desired, but when it finishes, it shows 0 Joules as energy consumed, which is clearly incorrect.

Furthermore, the PowerMonitor does not work: when you press the executable, a cmd window opens for an instant and then closes the next instant.

My specs:
Processor: AMD Ryzen 3 4300U with Radeon Graphics 2.70 GHz
RAM: 8GB
OS: Win11
I'm working with IntelliJ IDEA Community Edition v2022.3
I've got the Java JDK 21.0.1

<img width="756" alt="0 joules" src="https://github.com/joular/joularjx/assets/125913615/fff47bf0-2309-41bf-a3d8-61efcac480fe">

Thank you for your attention and everything that could help for this problem,
best regards.

**Comment by adelnoureddine** [comment]
Hi, on Windows, we use Intel Power Gagdet to get CPU power consumption.
This only works on Intel CPU (no AMD unfortunately).
On Linux AMD Ryzen works, and we're aiming for using another approach for CPU power on Windows, hopefully supporting AMD too.
But for now, on Windows, it's Intel only.
