### ISSUE TITLE
Joularjx does not profile other Java methods other main() method in Spring Boot application

### ISSUE THREAD

**Issue by pangteckchun** [joular/joularjx#66]
Hi, great work on Joularjx - an important piece in Green Software hence we are keen to make full use of it.

We are profiling the sample Pet Clinic Spring Boot app and noticed only the main() method gets profiled but other app specific methods are not. This happens even though we have specified the top most package name for the pet clinic app.

1. Please see the `config.properties` used.
1. And we built the PetClinic jar based on instructions found on https://github.com/spring-projects/spring-petclinic.
-- Are you able to provide me a location to upload the jar? it is 52MB and does not pass the Github upload restrictions of 25MB.
2. This is all done on my local Windows laptop running Windows 10 Enterprise, 12th Gen Intel Core i7.

In the meantime we will profile a non spring boot app to see and another internal spring boot app to compare.

This issue might be related to this same issue reported: https://github.com/joular/joularjx/issues/64

Thank you!
TC

**Comment by pangteckchun** [comment]
**joularjx-result** for PetClinic Spring Boot app - see zip.
Observations:
1. Only `main()` method is profiled
2. Same for **runtime** as well as for **total**
3. For **all-methods / runtime / methods** we noticed the power consumptions have the same values across the different JVM  methods. Is this expected? (reference `joularJX-42204-1709885257121-all-methods-power.csv`)
4. After shutting down the Spring Boot app, the **all-methods / total / methods** appear to have dynamic profiled values which seemed more 'real'. FYI.
5. Because we can't tell if (3) and (4) will apply to our Spring Boot app custom methods (since only main() is profiled), this might be a concern since we expect an app to run for prolonged periods without shutting down and we would like to profile its methods consumption while the app is in operation.

[42204-1709885214480.zip](https://github.com/joular/joularjx/files/14552659/42204-1709885214480.zip)

**Comment by adelnoureddine** [comment]
Thanks for reporting this issue, which needs te be analyzed further to get what's going on and why JoularJX is failing to provide energy data after the initial start.

In the mean time, did you check the proposed tweak in my [first comment](https://github.com/joular/joularjx/issues/64#issuecomment-1960958128) in issue #64 (putting while true instead of destroyvm)?

**Comment by adelnoureddine** [comment]
I managed to replicate the issue (no need to send me a jar, I compiled the one from petclinic's git).

If you change ```destroyvm()``` with ```true``` as in the commit #1dd0a64 (and recompile JoularJX), you should be able to get the energy consumption of other functions than ```main```.

**Comment by adelnoureddine** [comment]
You could try the proposed fix in branch [fixForApplicationServers](/joular/joularjx/tree/fixForApplicationServers), just download and recompile with Maven JoularJX in that branch.
I added a compiled binary here: [joularjx-2.8.2.zip](https://github.com/joular/joularjx/files/14556505/joularjx-2.8.2.zip)

There is a new config property for application servers which you need to set to true: ```application-server=true``` (by default it is false).

**Comment by pangteckchun** [comment]
Hi, thank you for the prompt responses. We appreciate this!!!
I downloaded the binary and changed `application-server=true` in **_config.properties_**.

**In summary:**
1. Runtime CSV is now 0 bytes and no lines are written to it 👎 (so this still a key issue).
2. Upon app shutdown, app / total is written with a CSV containing methods of the Petclinic application energy profiles (hurray! 👍) - but there are inconsistencies.
3. We did the same interactions on the webfront in all cases of testing: *Add owner, add a pet, add a visit, browse vets, brown owner*.
---
#### `overwrite-runtime-data=false`
- The app / runtime folder contains CSVs (32 CSVs written per minute) while the app is still running; this seemed to have corrected the issue of only profiling at start up time; but all the files are 0 bytes and empty.
![45296-app-runtime-csvs](https://github.com/joular/joularjx/assets/16695383/a7090b6a-388b-4793-9c21-f141ceecd516)

- The `app / total / .csv` contains methods called when interacting with PetClinic which looks legit! :-)
![45296-overwrite-runtime-true](https://github.com/joular/joularjx/assets/16695383/e5816e75-304b-4fde-9100-6191002484ad)

---
#### `overwrite-runtime-data=true`
-  The app / runtime folder contains 1 CSV (as expected) but as highlighted, it is 0 bytes and empty. The date/time stamp of the CSV gets updated upon modifications during the interactions 👍 
- If it helps, we observe a momentary **1kb --> 0kb** change of the CSV upon new file writes.
![48592-app-runtime-csvs](https://github.com/joular/joularjx/assets/16695383/16ea7403-e285-4bf9-8857-7fec7e3fca50)

- However, the `app / total / .csv` contains MUCH LESS methods calls, compare to setting `overwrite-runtime-data=false`.
![48592-overwrite-runtime-true](https://github.com/joular/joularjx/assets/16695383/78f9f22a-3c97-47ff-a1af-798211a16f70)

---
Hope the above helps in narrowing the issue further!

**Comment by adelnoureddine** [comment]
Thanks for the detailed update and investigation. I'll try to debug the issue but some of the numbers are expected due to the limitation of JoularJX:
- We check the stacktrace of each thread every 10ms, so methods running shorter or that happen to end before the next observation (or start just after) will not be noticed. Therefore, they will not be allocated energy consumption by our statistical approach.

The petclinic app has many of these small methods, which explains why you have fewer methods in the second run than the first. All the smaller energy methods (0.x) are usually observed once or twice, and might have missed the observation.

**Comment by pangteckchun** [comment]
Thank you @adelnoureddine!
Noted on the context that some methods may run shorter than 10ms. Useful knowledge.

Looking forward to your further inputs.
If there is any more scenarios you would like us to test, we would be happy to do so.
